### ISSUE TITLE
Property 'string' of object #<Object> is not a function

### ISSUE THREAD

**Issue by Truemedia** [simbo/auto-plug#4] opened 2015-12-22 16:01 UTC
Get this when launching with a slush (gulp) file that relies on this library.

Here is the full output:
/web/node_test/slush-blueprints/node_modules/auto-plug/node_modules/defined-options/node_modules/validate-by-shorthand/lib/validate-value.js:16
    if (is.string(validate)) {
           ^
TypeError: Property 'string' of object #<Object> is not a function
    at validateValue (/web/node_test/slush-blueprints/node_modules/auto-plug/node_modules/defined-options/node_modules/validate-by-shorthand/lib/validate-value.js:16:12)
    at AutoPlug.setOptions (/web/node_test/slush-blueprints/node_modules/auto-plug/lib/auto-plug.js:99:15)
    at new AutoPlug (/web/node_test/slush-blueprints/node_modules/auto-plug/lib/auto-plug.js:89:10)
    at module.exports (/web/node_test/slush-blueprints/node_modules/auto-plug/index.js:11:20)
    at Object.<anonymous> (/web/node_test/slush-blueprints/tasks/categories.js:3:39)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Looks like one of the tests for a dependency of this library has failed (defined-options).

**Comment by Truemedia** [comment] 2015-12-22 16:07
Tried installing the latest version of auto-plug, defined-options, validate-by-shorthand, but same issue.

Looks like it is one of the tests for validate-by-shorthand. Not used that library before so not sure what the fix would be.

**Comment by simbo** [comment] 2015-12-23 09:11
Which Node version are you using?

**Comment by simbo** [comment] 2016-01-17 12:53
As you are not answering and i can't reproduce that error, i'm closing this.

**Closed as completed by simbo** 2016-01-17 12:53 UTC
